---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    org: application-a
    class: service-a
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 2
  selector:
    matchLabels:
      org: application-a
      class: service-a
  template:
    metadata:
      labels:
        org: application-a
        class: service-a
    spec:
      containers:
      - name: service-a
        image: larse514/myservice
---
apiVersion: v1
kind: Pod
metadata:
  name: client-a
  labels:
    org: application-a
    class: client-a
spec:
  containers:
  - name: micro-a
    image: larse514/myclient
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    org: application-b
    class: service-b
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 2
  selector:
    matchLabels:
      org: application-b
      class: service-b
  template:
    metadata:
      labels:
        org: application-b
        class: service-b
    spec:
      containers:
      - name: service-b
        image: larse514/myservice
---
apiVersion: v1
kind: Pod
metadata:
  name: client-b
  labels:
    org: application-b
    class: client-b
spec:
  containers:
  - name: micro-b
    image: larse514/myclient